name: hitsterclone
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  gif: ^2.3.0
  change_app_package_name: ^1.5.0
  provider: ^6.1.5+1
  flutter_web_auth_2: ^4.1.0
  crypto: ^3.0.6
  wave: ^0.2.2
  rename: ^3.1.0
  flutter_launcher_icons: ^0.14.4
  font_awesome_flutter: ^10.11.0
  shared_preferences: ^2.3.2
  confetti: ^0.8.0
  flutter_dotenv: ^5.1.0
  flutter_animate: ^4.5.2

flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/data.json
    - assets/gifs/
